version: "3.3"
services:
  spending:
    restart: always
    image: 47.97.254.68:5000/spending:latest
    build: ../
    volumes:
      - ../src:/app
    links:
      - redis
      - mysql
    environment:
      STAGE: production

  redis:
    image: redis:alpine
    restart: always

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    links:
      - "spending"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: spending
      MYSQL_PASSWORD: 123456
    restart: always
