version: "3.3"
services:
  web:
    restart: always
    image: spending
    build: ../
    volumes:
      - ../src:/app
#    ports:
#      - "8008:8008"
    links:
      - redis
      - mysql
    environment:
      STAGE: development

  redis:
    image: "redis:alpine"
    restart: always

  nginx:
    image: "nginx"
    restart: always
    ports:
      - "80:80"
    links:
      - "web"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./cert/6541345_www.kkone.top.key:/etc/nginx/6541345_www.kkone.top.key"
      - "./cert/6541345_www.kkone.top.pem:/etc/nginx/6541345_www.kkone.top.pem"

  mysql:
    image: "mysql"
#    ports:
#      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456hk
      MYSQL_DATABASE: spending
      MYSQL_PASSWORD: 123456hk
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: always
