clone:
  git:
    # 可以自定义
    image: woodpeckerci/plugin-git
#    environment:
#      - DRONE_REMOTE_URL=${DRONE_REMOTE_URL}
#      - DRONE_WORKSPACE=${DRONE_WORKSPACE}
#      - DRONE_BUILD_EVENT=${DRONE_BUILD_EVENT}
#      - DRONE_COMMIT_SHA=${DRONE_COMMIT_SHA}
#      - DRONE_COMMIT_REF=${DRONE_COMMIT_REF}
#    network: "host"
    commands:
      - git config --global http.version HTTP/1.1
      - git config --global http.proxy 'http://127.0.0.1:1087'
      - git config --global https.proxy 'https://127.0.0.1:1087'

pipeline:

  lint:
    image: 127.0.0.1:5000/lint:v1
    commands:
    - cd src
    - ls -al
    - yapf -dr . | (! grep '.')
    - isort . --check-only --diff

  build_docker_image:
    image: plugins/docker
    insecure: true
    registry: 172.21.0.1:5000
    repo: 172.21.0.1:5000/spending
    tags:
      - latest
    when:
      event: tag

  web_hook:
    image: plugins/webhook
    urls:
      - http://121.43.135.49:8009/web_hook/accept?name=spending
    method: GET
    when:
      event: tag