pipeline:

  lint:
    image: registry.kkone.top:5000/lint:v1
    commands:
    - cd src
    - ls -al
    - yapf -dr . | (! grep '.')
    - isort . --check-only --diff

  build_docker_image:
    image: plugins/docker
    registry: registry.kkone.top:5000
    repo: registry.kkone.top:5000/spending
    tags:
    - v1
    when:
      event: push
