clone:
  git:
    # 可以自定义
    image: 127.0.0.1:5000/ci-git
    environment:
      - CI_COMMIT_TARGET_BRANCH
      - CI_REPO_REMOTE



pipeline:
#  clone:
#    image: woodpeckerci/plugin-git
#    commands:
#      - git config --global http.version HTTP/1.1

  lint:
    image: 127.0.0.1:5000/lint:v1
    commands:
    - ls -al
    - cd src
    - yapf -dr . | (! grep '.')
    - isort . --check-only --diff

  build_docker_image:
    image: plugins/docker
    insecure: true
    registry: 172.21.0.1:5000
    repo: 172.21.0.1:5000/spending
    tags:
      - latest
    when:
      event: tag

  web_hook:
    image: plugins/webhook
    urls:
      - http://121.43.135.49:8009/web_hook/accept?name=spending
    method: GET
    when:

      event: tag
