pipeline:

  lint:
    image: 127.0.0.1:5000/lint:v1
    commands:
    - cd src
    - ls -al
    - yapf -dr . | (! grep '.')
    - isort . --check-only --diff

  build_docker_image:
    image: plugins/docker
    registry: 127.0.0.1:5000
    repo: 127.0.0.1:5000/oneio/spending
    cache_from: 127.0.0.1:5000/oneio/spending:v2
    tags:
    - v2
    when:
      event: push
