pipeline:

  lint:
    image: 127.0.0.1:5000/lint:v1
    commands:
    - cd src
    - ls -al
    - yapf -dr . | (! grep '.')
    - isort . --check-only --diff

  build_docker_image:
    image: plugins/docker
    insecure: true
    registry: 172.21.0.1:5000
    repo: 172.21.0.1:5000/spending
    tags:
      - v1
    when:
      event: push
