pipeline:
  build_docker_image:
    image: plugins/docker
    registry: 127.0.0.1:5000
    repo: 127.0.0.1:5000/spending
    cache_from: 127.0.0.1:5000/spending:latest
    tags:
    - ${DRONE_COMMIT_SHA}
    - latest
    when:
      event: push