pipeline:

  lint:
    image: 127.0.0.1:5000/lint:v1
    commands:
    - cd src
    - ls -al
    - yapf -dr . | (! grep '.')
    - isort . --check-only --diff

  build_docker_image:
    image: plugins/docker
    commands:
      - echo { "insecure-registries""[:]" ["47.97.254.68:5000"] } > /etc/docker/daemon.json
    registry: 47.97.254.68:5000
    repo: 47.97.254.68:5000/spending
    cache_from: 47.97.254.68:5000/spending:v2
    tags:
    - v2
    when:
      event: push
