pipeline:

  clone:
    git:
      image: plugins/git
      commands:
        - git config --global http.proxy 'http://127.0.0.1:1087'
        - git config --global https.proxy 'https://127.0.0.1:1087'

  lint:
    image: 127.0.0.1:5000/lint:v1
    commands:
    - cd src
    - ls -al
    - yapf -dr . | (! grep '.')
    - isort . --check-only --diff

  build_docker_image:
    image: plugins/docker
    insecure: true
    registry: 172.21.0.1:5000
    repo: 172.21.0.1:5000/spending
    tags:
      - v1
    when:
      event: tag

  web_hook:
    image: plugins/webhook
    urls:
      - http://121.43.135.49:8009/web_hook/accept?spending
    method: GET
    when:
      event: tag